import csv
file = open("student.csv",'a')
file.write("Name\t")
file.write("Age\t")
file.write("Class\t\n")
file.write("Htet Arkar\t")
file.write("15\t")
file.write("Grade(9)-B\n")
file.write("Aye Aye\t")
file.write("16\t")
file.write("Grade(9)-B\n")
file.close()
file = open("student.csv",'r')
print(file.read())
file.close()