name=input("Entr your nmae: ")
print("Hello",name)

num=int(input("Enter a number: "))
print("Your square.0d number:",num**2)

print()
print()
na=input("Enter your name: ")
age=input("Enter you age: ")
addres=input("Enter your address: ")
job=input("Enter your job: ")
print()
print()
print(na,"'s info")
print('Name: ',na)
print('Your age:',age)
print('Your address:',addres)
print('Your job:',job)
