# Generated by Django 3.2.5 on 2021-12-10 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tutorial Title', max_length=200)),
                ('content', models.TextField(help_text='Tutorial content')),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
